### PR TITLE
Add property for changing initial flashlight state

### PR DESCRIPTION
**Pull request by wiruzx**

### CODE REVIEW

**Comment by jpsim** [comment]
Nice work! What are your thoughts on moving the functionality from `setupFlashButtonForFlashlightEnabled:` to `setFlashlightEnabled:`? This way, setting the property will also make the necessary changes.

**Comment by wiruzx** [comment]
I like the idea, but if you changed this `flashlightEnabled` before view will appear, it wouldn't work, because the `currentDevice` isn't ready yet. So I couldn't just put all flashlight logic into setter of this property.

**Comment by jpsim** [comment]
> it wouldn't work, because the currentDevice isn't ready yet

Good point, although if you just have an early return in the setter if `currentDevice == nil`, then call the setter again in `viewWillAppear`, you won't do unnecessary work multiple times while still keeping the niceness of setting `flashlightEnabled` do what you expect as the picker is running.

**Comment by wiruzx** [comment]
Make sense. I'll fix this

**Comment by wiruzx** [comment]
@jpsim ping :)

**Comment by jpsim** [comment]
Great work, thanks!

**Pull request merged**
